name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/configure_awx.yaml
          directory: ./
          inventory: |
            [all]
            localhost
          vault_password: ${{secrets.VAULT_PASSWORD}}
          requirements: galaxy-requirements.yaml
